version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: fpl
      POSTGRES_USER: fpl
      POSTGRES_PASSWORD: fpl
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_fpl_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - fpl-net
  adminer:
    image: adminer:latest
    ports:
      - "85:8080"
    restart: always
    networks:
      - fpl-net
volumes:
  postgres_fpl_volume:
networks:
  fpl-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.5.0/24
          gateway: 172.168.5.1