import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import React from 'react';
import { Layout } from "antd";
import 'react-json-pretty/themes/monikai.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body style={{ height: '100vw', margin: 0, padding: 0 }} className={inter.className}>
        <AntdRegistry>
          <Layout style={{ width: '100%', height: '100%', backgroundColor: '#ffffff' }}>
            {children}
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
